### ISSUE TITLE
Have weigh bin on the homepage with bin ID as an option for its input. Under bin info/weigh bin removed bin Id option, BUT DISPLAY THE BIN ID

### ISSUE THREAD

**Issue by mygoodirishman** [codeSourc3/JCCC-Zero-Waste-Inventory-System-#14]

**Comment by codeSourc3** [comment]
Do you mean home page as in the index.html, or home page as in the dashboard?

**Comment by mygoodirishman** [comment]
dashboard

**Comment by codeSourc3** [comment]
Wouldn't it make more sense to leave it where it is and just have the site remember which bin id they want to weigh?
